version: "3.8"

services:
  redis:
    image: redis
    container_name: redis
    ports:
      - "6379:6379"
    volumes:
      - redis:/data
  redisexplorer:
    image: rediscommander/redis-commander:latest
    container_name: liquidation-bot_redis_DEV
    ports:
      - "8081:8081"
    environment:
      REDIS_HOSTS: "redis"



volumes:
  redis: